### ISSUE TITLE
Update SDK

### ISSUE THREAD

**Issue by fephil** [BatchLabs/cordova-plugin#3]
Hi,

Is there a roadmap to update the Cordova SDK to match the IOS/Android latest version? For example the In-App Campaigns would be useful.

Thanks.

**Comment by abarisain** [comment]
Hello,

This is definitely planned, but I unfortunately don't have a timeframe for that.

We're also working on a way to make it so the underlying Batch version is easily updatable without waiting for us to update this plugin: This is already possible for Android, but not quite there yet for iOS.

**Comment by fephil** [comment]
Thanks for letting me know @abarisain

**Comment by fephil** [comment]
Hi @abarisain, is there any update on when the Cordova plugin will be updated?

**Comment by abarisain** [comment]
The good news is that we're currently working on totally reworking it and making it so that the underlying SDK can be updated without waiting for a new cordova release on our side.

Unfortunately I don't have a timeline, but I can say that it's coming _soon_ :)

PS: It will be cordova-android 7.0 and higher only. unfortunately cordova broke the api in such a way that we can't make the plugin available on both 7.0 and lower

**Comment by abarisain** [comment]
Hello!

The 2.0.0 version solves this. It also contains instruction on how to update the native SDKs yourself.
We're currently rolling it out, code and npm releases are done, you can expect the official documentation to be fully updated next week.
