### ISSUE TITLE
 Android O Notification Channels support

### ISSUE THREAD

**Issue by fephil** [BatchLabs/cordova-plugin#4]
Hi. Are there any plans to support Android 8 Notification channels soon?

Thanks.

**Comment by abarisain** [comment]
Hi,

If you update Batch's aar with the latest 1.10 version in the android folder ( https://github.com/BatchLabs/cordova-plugin/tree/master/SDK/batch-cordova-plugin/src/android ), you'll be able to target API 26  

If you want to create your own channels, that will unfortuately be very difficult with Cordova, since this is stuff the app does in the background, without ever starting any JS from cordova

**Comment by abarisain** [comment]
Hi,

I think you're starting to get the hang of it: 2.0.0 fixes this!
